engines:
  golint:
    enabled: true
  govet:
    enabled: true
  gofmt:
    enabled: true
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
  - "**.sh"
  - "**.md"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
