engines:
  rubocop:
    enabled: true
    #checks:
    #  Rubocop/Metrics/ClassLength:
    #    enabled: false
  golint:
    enabled: true
  govet:
    enabled: true
  gofmt:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
