language: go
sudo: false
go:
  - 1.x
  - tip

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

before_install:
  - go get -t -v ./...

script:
  - ./test.sh 

after_success:
  - bash <(curl -s https://codecov.io/bash)
