codecov:
  notify:
    require_ci_to_pass: yes

# Team Yaml
coverage:
  round: down
  precision: 5

# Repository Yaml
coverage:
  round: up
  range: 0..10

# Used in Codecov after updating
coverage:
  round: up
  range: 0..10
  precision: 5

ignore:
  - "test*.sh"       # wildcards accepted
  - "**/*.sh"        # g

comment:
  layout: "reach, diff, flags, files, changes, footer"
  behavior: default
  require_changes: no

